# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 950))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/appointment-book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(225, 228, 234);")
        self.centralwidget.setObjectName("centralwidget")
        self.applicationFrame = QtWidgets.QFrame(self.centralwidget)
        self.applicationFrame.setGeometry(QtCore.QRect(20, 30, 1881, 1021))
        self.applicationFrame.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius: 14px;")
        self.applicationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.applicationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.applicationFrame.setObjectName("applicationFrame")
        self.headerFrame = QtWidgets.QFrame(self.applicationFrame)
        self.headerFrame.setGeometry(QtCore.QRect(29, 20, 1821, 61))
        self.headerFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 14px;")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.headerFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1821, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(13, 0, 13, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(220, 50))
        self.widget.setObjectName("widget")
        self.logoLabel = QtWidgets.QLabel(self.widget)
        self.logoLabel.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/plannerLogo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.logoText = QtWidgets.QLabel(self.widget)
        self.logoText.setGeometry(QtCore.QRect(74, 15, 161, 31))
        self.logoText.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logoText.setFont(font)
        self.logoText.setObjectName("logoText")
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(600, 50))
        self.widget_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"    width: 115px;\n"
"    height: 45px;\n"
"    font-size:10pt;\n"
"}\n"
"\n"
"QPushButton::checked {\n"
"    background-color: rgb(24, 63, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(59, 0, 451, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, 11)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.appointmentsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.appointmentsButton.setMinimumSize(QtCore.QSize(140, 0))
        self.appointmentsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.appointmentsButton.setCheckable(True)
        self.appointmentsButton.setObjectName("appointmentsButton")
        self.horizontalLayout_3.addWidget(self.appointmentsButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.patientsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.patientsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.patientsButton.setCheckable(True)
        self.patientsButton.setObjectName("patientsButton")
        self.horizontalLayout_3.addWidget(self.patientsButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.statisticsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.statisticsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statisticsButton.setCheckable(True)
        self.statisticsButton.setObjectName("statisticsButton")
        self.horizontalLayout_3.addWidget(self.statisticsButton)
        self.horizontalLayout_2.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(150, 50))
        self.widget_3.setStyleSheet("QPushButton {\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    border-radius: 20px;\n"
"    background-color: rgb(240, 240, 240);    \n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(132, 132, 132);\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(80, 0, 71, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(17, 0, 11, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.settingsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.settingsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsButton.setStyleSheet("")
        self.settingsButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon1)
        self.settingsButton.setIconSize(QtCore.QSize(25, 25))
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_4.addWidget(self.settingsButton)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.addNewPatientButton = QtWidgets.QPushButton(self.applicationFrame)
        self.addNewPatientButton.setGeometry(QtCore.QRect(1670, 100, 180, 50))
        self.addNewPatientButton.setMaximumSize(QtCore.QSize(180, 50))
        self.addNewPatientButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewPatientButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"    width: 115px;\n"
"    height: 45px;\n"
"    font-size:10pt;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(132, 132, 132);\n"
"}")
        self.addNewPatientButton.setObjectName("addNewPatientButton")
        self.buttonsFrame = QtWidgets.QFrame(self.applicationFrame)
        self.buttonsFrame.setGeometry(QtCore.QRect(20, 160, 1841, 71))
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.buttonsFrame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(-1, 0, 1831, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_4)
        self.frame_4.setMinimumSize(QtCore.QSize(500, 70))
        self.frame_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 50px;\n"
"}\n"
"\n"
"QPushButton::checked {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_4)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(9, 0, 491, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.filterButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.filterButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filterButton.setFont(font)
        self.filterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons8-filter-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon2)
        self.filterButton.setIconSize(QtCore.QSize(48, 48))
        self.filterButton.setCheckable(True)
        self.filterButton.setObjectName("filterButton")
        self.horizontalLayout_6.addWidget(self.filterButton)
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.searchButton.setMaximumSize(QtCore.QSize(110, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.searchButton.setFont(font)
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons8-search-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon3)
        self.searchButton.setIconSize(QtCore.QSize(48, 48))
        self.searchButton.setCheckable(True)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_6.addWidget(self.searchButton)
        self.dailyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.dailyButton.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dailyButton.setFont(font)
        self.dailyButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons8-calendar-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dailyButton.setIcon(icon4)
        self.dailyButton.setIconSize(QtCore.QSize(48, 48))
        self.dailyButton.setCheckable(True)
        self.dailyButton.setObjectName("dailyButton")
        self.horizontalLayout_6.addWidget(self.dailyButton)
        self.monthlyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.monthlyButton.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.monthlyButton.setFont(font)
        self.monthlyButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.monthlyButton.setIcon(icon4)
        self.monthlyButton.setIconSize(QtCore.QSize(48, 48))
        self.monthlyButton.setCheckable(True)
        self.monthlyButton.setObjectName("monthlyButton")
        self.horizontalLayout_6.addWidget(self.monthlyButton)
        self.horizontalLayout.addWidget(self.frame_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.applicationFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 240, 1841, 721))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.monthlyAppointsTable = QtWidgets.QTableWidget(self.page1)
        self.monthlyAppointsTable.setGeometry(QtCore.QRect(75, 71, 1691, 631))
        self.monthlyAppointsTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(74, 213, 208); \n"
"    border: 0.5px solid rgb(216, 216, 216); \n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-right: 0.5px solid rgb(216, 216, 216)\n"
"}\n"
"\n"
"")
        self.monthlyAppointsTable.setObjectName("monthlyAppointsTable")
        self.monthlyAppointsTable.setColumnCount(7)
        self.monthlyAppointsTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthlyAppointsTable.setHorizontalHeaderItem(6, item)
        self.monthlyAppointsTable.horizontalHeader().setDefaultSectionSize(238)
        self.monthlyAppointsTable.verticalHeader().setDefaultSectionSize(97)
        self.monthYearLabel = QtWidgets.QLabel(self.page1)
        self.monthYearLabel.setGeometry(QtCore.QRect(760, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.monthYearLabel.setFont(font)
        self.monthYearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monthYearLabel.setObjectName("monthYearLabel")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.page1)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(990, 10, 101, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previousMonthButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.previousMonthButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previousMonthButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(235, 235, 235);\n"
"        border-radius: 20px; /* Polovina širine/visine dugmeta za savršeno okrugli oblik */\n"
"        min-width: 40px; /* Veličina dugmeta */\n"
"        min-height: 40px;\n"
"    }\n"
"\n"
"QPushButton::checked {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.previousMonthButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons8-sort-left-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousMonthButton.setIcon(icon5)
        self.previousMonthButton.setObjectName("previousMonthButton")
        self.horizontalLayout_5.addWidget(self.previousMonthButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.nextMonthButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.nextMonthButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextMonthButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(235, 235, 235);\n"
"        border-radius: 20px; /* Polovina širine/visine dugmeta za savršeno okrugli oblik */\n"
"        min-width: 40px; /* Veličina dugmeta */\n"
"        min-height: 40px;\n"
"    }\n"
"\n"
"QPushButton::checked {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.nextMonthButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons8-arrow-right-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextMonthButton.setIcon(icon6)
        self.nextMonthButton.setObjectName("nextMonthButton")
        self.horizontalLayout_5.addWidget(self.nextMonthButton)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.dailyAppointsTable = QtWidgets.QTableWidget(self.page2)
        self.dailyAppointsTable.setGeometry(QtCore.QRect(40, 70, 1761, 291))
        self.dailyAppointsTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(74, 213, 208); \n"
"    border: 0.5px solid rgb(216, 216, 216); \n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-right: 0.5px solid rgb(216, 216, 216)\n"
"}")
        self.dailyAppointsTable.setObjectName("dailyAppointsTable")
        self.dailyAppointsTable.setColumnCount(15)
        self.dailyAppointsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyAppointsTable.setHorizontalHeaderItem(14, item)
        self.dailyAppointsTable.horizontalHeader().setDefaultSectionSize(116)
        self.dailyAppointsTable.verticalHeader().setVisible(False)
        self.dailyAppointsTable.verticalHeader().setDefaultSectionSize(239)
        self.dateLabel = QtWidgets.QLabel(self.page2)
        self.dateLabel.setGeometry(QtCore.QRect(730, 20, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateLabel.setFont(font)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.tableWidgetPatients = QtWidgets.QTableWidget(self.page3)
        self.tableWidgetPatients.setGeometry(QtCore.QRect(370, 30, 1071, 641))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tableWidgetPatients.setFont(font)
        self.tableWidgetPatients.setStyleSheet("\n"
"QHeaderView {\n"
"        font-size: 16pt;  /* Veličina fonta za zaglavlje */\n"
"    }\n"
"\n"
"QHeaderView::section {\n"
"        border: 1px solid rgb(182, 182, 182); \n"
"        background-color: rgb(74, 213, 208); \n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #888;\n"
"    min-height: 30px;  /* ovo je ono što skraćuje */\n"
"    max-height: 50px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.tableWidgetPatients.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidgetPatients.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetPatients.setAlternatingRowColors(True)
        self.tableWidgetPatients.setObjectName("tableWidgetPatients")
        self.tableWidgetPatients.setColumnCount(4)
        self.tableWidgetPatients.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPatients.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetPatients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPatients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPatients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPatients.setHorizontalHeaderItem(3, item)
        self.tableWidgetPatients.horizontalHeader().setDefaultSectionSize(263)
        self.tableWidgetPatients.horizontalHeader().setMinimumSectionSize(51)
        self.tableWidgetPatients.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetPatients.verticalHeader().setMinimumSectionSize(38)
        self.stackedWidget.addWidget(self.page3)
        self.addNewAppointmentButton = QtWidgets.QPushButton(self.applicationFrame)
        self.addNewAppointmentButton.setGeometry(QtCore.QRect(1439, 100, 211, 50))
        self.addNewAppointmentButton.setMaximumSize(QtCore.QSize(220, 50))
        self.addNewAppointmentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewAppointmentButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"    width: 115px;\n"
"    height: 45px;\n"
"    font-size:10pt;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(132, 132, 132);\n"
"}")
        self.addNewAppointmentButton.setObjectName("addNewAppointmentButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MedicalBooker"))
        self.logoText.setText(_translate("MainWindow", "Appointments"))
        self.appointmentsButton.setText(_translate("MainWindow", "Appointments"))
        self.patientsButton.setText(_translate("MainWindow", "Patients"))
        self.statisticsButton.setText(_translate("MainWindow", "Statistics"))
        self.addNewPatientButton.setText(_translate("MainWindow", "+ Add New Patient"))
        self.filterButton.setText(_translate("MainWindow", "  Filter"))
        self.searchButton.setText(_translate("MainWindow", "  Search"))
        self.dailyButton.setText(_translate("MainWindow", "  Daily"))
        self.monthlyButton.setText(_translate("MainWindow", "  Monthly"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Monday"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tuesday"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Wednesday"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thursday"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Friday"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Saturday"))
        item = self.monthlyAppointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sunday"))
        self.monthYearLabel.setText(_translate("MainWindow", "Decembar, 2024"))
        self.dateLabel.setText(_translate("MainWindow", "Ponedjeljak, 24.10.2024"))
        item = self.tableWidgetPatients.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.tableWidgetPatients.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Years"))
        item = self.tableWidgetPatients.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidgetPatients.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone number"))
        self.addNewAppointmentButton.setText(_translate("MainWindow", "+ Add New Appointment"))
import images
