# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newAppointment.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        Dialog.setMinimumSize(QtCore.QSize(400, 500))
        Dialog.setMaximumSize(QtCore.QSize(400, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/appointment-book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"border-radius: 15px;")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 341, 91))
        self.widget.setObjectName("widget")
        self.patientLabel = QtWidgets.QLabel(self.widget)
        self.patientLabel.setGeometry(QtCore.QRect(10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patientLabel.setFont(font)
        self.patientLabel.setObjectName("patientLabel")
        self.comboBoxPatients = QtWidgets.QComboBox(self.widget)
        self.comboBoxPatients.setGeometry(QtCore.QRect(10, 30, 301, 31))
        self.comboBoxPatients.setStyleSheet("QComboBox {\n"
"    background-color: rgb(255, 255, 255);    /* Pozadina kada nije otvoren */\n"
"    color: #333333;               /* Boja teksta */\n"
"    border-radius: 5px;           /* Zaobljenost ivica */\n"
"    padding: 5px;                 /* Unutrašnji razmak */\n"
"    font-size: 14px;              /* Veličina fonta */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgb(222, 222, 222);    /* Pozadina kada je miš iznad */\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 2px solid #5c5c5c; /* Ivice između dugmeta za otvaranje */\n"
"    width: 30px;                     /* Širina dugmeta za otvaranje */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons8-drop-down-16.png);   /* Putanja do slike za strelicu nadole */\n"
"    width: 16px;                  /* Širina strelice */\n"
"    height: 16px;                 /* Visina strelice */\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;    /* Pozadina padajuće liste */\n"
"    selection-background-color: rgb(185, 185, 185);  /* Boja pozadine selektovanog elementa */\n"
"    selection-color: rgb(39, 39, 39);     /* Boja teksta selektovanog elementa */\n"
"    font-size: 14px;              /* Veličina fonta za stavke u padajućoj listi */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"")
        self.comboBoxPatients.setCurrentText("")
        self.comboBoxPatients.setObjectName("comboBoxPatients")
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(20, 110, 341, 91))
        self.widget1.setObjectName("widget1")
        self.dateLabel = QtWidgets.QLabel(self.widget1)
        self.dateLabel.setGeometry(QtCore.QRect(10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateLabel.setFont(font)
        self.dateLabel.setObjectName("dateLabel")
        self.dateText = QtWidgets.QLabel(self.widget1)
        self.dateText.setGeometry(QtCore.QRect(10, 40, 201, 31))
        self.dateText.setStyleSheet(" background-color: rgb(255, 255, 255);    /* Pozadina kada nije otvoren */\n"
"    color: #333333;               /* Boja teksta */\n"
"    border-radius: 5px;           /* Zaobljenost ivica */\n"
"    padding: 5px;                 /* Unutrašnji razmak */\n"
"    font-size: 14px;              /* Veličina fonta */")
        self.dateText.setText("")
        self.dateText.setObjectName("dateText")
        self.saveNewAppointmentButton = QtWidgets.QPushButton(Dialog)
        self.saveNewAppointmentButton.setGeometry(QtCore.QRect(200, 420, 161, 50))
        self.saveNewAppointmentButton.setMaximumSize(QtCore.QSize(170, 50))
        self.saveNewAppointmentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveNewAppointmentButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(74, 213, 208);\n"
"    color: rgb(255, 255, 255);\n"
"    width: 115px;\n"
"    height: 45px;\n"
"    font-size:10pt;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(132, 132, 132);\n"
"}")
        self.saveNewAppointmentButton.setObjectName("saveNewAppointmentButton")
        self.widget3 = QtWidgets.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(20, 310, 341, 91))
        self.widget3.setObjectName("widget3")
        self.treatmentLabel = QtWidgets.QLabel(self.widget3)
        self.treatmentLabel.setGeometry(QtCore.QRect(10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treatmentLabel.setFont(font)
        self.treatmentLabel.setObjectName("treatmentLabel")
        self.comboBoxTreatment = QtWidgets.QComboBox(self.widget3)
        self.comboBoxTreatment.setGeometry(QtCore.QRect(10, 30, 301, 31))
        self.comboBoxTreatment.setStyleSheet("QComboBox {\n"
"    background-color: rgb(255, 255, 255);    /* Pozadina kada nije otvoren */\n"
"    color: #333333;               /* Boja teksta */\n"
"    border-radius: 5px;           /* Zaobljenost ivica */\n"
"    padding: 5px;                 /* Unutrašnji razmak */\n"
"    font-size: 14px;              /* Veličina fonta */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgb(222, 222, 222);    /* Pozadina kada je miš iznad */\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 2px solid #5c5c5c; /* Ivice između dugmeta za otvaranje */\n"
"    width: 30px;                     /* Širina dugmeta za otvaranje */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons8-drop-down-16.png);   /* Putanja do slike za strelicu nadole */\n"
"    width: 16px;                  /* Širina strelice */\n"
"    height: 16px;                 /* Visina strelice */\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;    /* Pozadina padajuće liste */\n"
"    selection-background-color: rgb(185, 185, 185);  /* Boja pozadine selektovanog elementa */\n"
"    selection-color: rgb(39, 39, 39);     /* Boja teksta selektovanog elementa */\n"
"    font-size: 14px;              /* Veličina fonta za stavke u padajućoj listi */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"")
        self.comboBoxTreatment.setCurrentText("")
        self.comboBoxTreatment.setObjectName("comboBoxTreatment")
        self.widget1_2 = QtWidgets.QWidget(Dialog)
        self.widget1_2.setGeometry(QtCore.QRect(20, 210, 341, 91))
        self.widget1_2.setObjectName("widget1_2")
        self.timeLabel = QtWidgets.QLabel(self.widget1_2)
        self.timeLabel.setGeometry(QtCore.QRect(10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.comboBoxTime = QtWidgets.QComboBox(self.widget1_2)
        self.comboBoxTime.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.comboBoxTime.setStyleSheet("QComboBox {\n"
"    background-color: rgb(255, 255, 255);    /* Pozadina kada nije otvoren */\n"
"    color: #333333;               /* Boja teksta */\n"
"    border-radius: 5px;           /* Zaobljenost ivica */\n"
"    padding: 5px;                 /* Unutrašnji razmak */\n"
"    font-size: 14px;              /* Veličina fonta */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgb(222, 222, 222);    /* Pozadina kada je miš iznad */\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 2px solid #5c5c5c; /* Ivice između dugmeta za otvaranje */\n"
"    width: 30px;                     /* Širina dugmeta za otvaranje */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons8-drop-down-16.png);   /* Putanja do slike za strelicu nadole */\n"
"    width: 16px;                  /* Širina strelice */\n"
"    height: 16px;                 /* Visina strelice */\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;    /* Pozadina padajuće liste */\n"
"    selection-background-color: rgb(185, 185, 185);  /* Boja pozadine selektovanog elementa */\n"
"    selection-color: rgb(39, 39, 39);     /* Boja teksta selektovanog elementa */\n"
"    font-size: 14px;              /* Veličina fonta za stavke u padajućoj listi */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"")
        self.comboBoxTime.setCurrentText("")
        self.comboBoxTime.setObjectName("comboBoxTime")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Appointment"))
        self.patientLabel.setText(_translate("Dialog", "Patient"))
        self.comboBoxPatients.setPlaceholderText(_translate("Dialog", "Odaberi Grad"))
        self.dateLabel.setText(_translate("Dialog", "Date"))
        self.saveNewAppointmentButton.setText(_translate("Dialog", "Save Appointment"))
        self.treatmentLabel.setText(_translate("Dialog", "Treatment"))
        self.comboBoxTreatment.setPlaceholderText(_translate("Dialog", "Odaberi Grad"))
        self.timeLabel.setText(_translate("Dialog", "Time"))
        self.comboBoxTime.setPlaceholderText(_translate("Dialog", "Odaberi Grad"))
import images
